---
# tasks file for theme3.3ontologies

- include: pato.yml
- include: the_gene_ontology.yml
- include: planteomeontologies.yml
- include: protein_ontology.yml
- include: plant_phenology_ontology.yml
- include: genotype_ontology.yml
- include: chebi_ontology.yml
- include: floral_phenotype_ontology.yml
- include: units_of_measurement_ontology.yml
- include: clinical_measurement_ontology.yml
- include: anatomical_entity_ontology.yml
- include: biological_spatial_ontology.yml
- include: agronomy_ontology.yml
- include: genetic_interval_ontology.yml